

ConvertTo-Html -InputObject (Get-Date)

Get-Alias | ConvertTo-Html | Out-File aliases.htm
Invoke-Item aliases.htm

Get-Process |
ConvertTo-Html -Property Name, Path, Company -Title "Process Information" |
Out-File proc.htm
Invoke-Item proc.htm

Get-Service | ConvertTo-Html -CssUri "G:\PS-Test\myStyleCode1.css" | Out-File service.htm
Invoke-Item service.htm

Get-Service | ConvertTo-Html -As LIST | Out-File services.htm

Get-Date | ConvertTo-Html -Fragment 

$htmlParams = @{
  Title = "Windows Services: Localhost"
  Body = Get-Date
  PreContent = "Generated by SWE"
  PostContent = "For details, contact SWE."
}
Get-Service A* |
ConvertTo-Html @htmlParams |
Out-File Services.htm
Invoke-Item Services.htm

Get-Service | ConvertTo-HTML -Meta @{
  refresh=10
  author="SWE"
  keywords="PowerShell, HTML, ConvertTo-HTML"
} -Charset "UTF-8" | head
